config/routes.rb
Rails.application.routes.draw do
  resources :emails

  resources :neighborhoods

  root "welcome#index"

  get 'email' => 'welcome#email'

  get 'thanks' => 'welcome#thanks'

end

app/models/email.rb
class Email < ActiveRecord::Base
	validates :firstname, presence: true
	validates :lastname, presence: true
	validates :email_address, presence: true
	validates :email_address, uniqueness: true
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_email, only: [:show, :edit, :update, :destroy]

  # GET /emails
  # GET /emails.json
  def index
    @emails = Email.all
  end

  # GET /emails/1
  # GET /emails/1.json
  def show
  end

  # GET /emails/new
  def new
    @email = Email.new
  end

  # GET /emails/1/edit
  def edit
  end

  # POST /emails
  # POST /emails.json
  def create
    @email = Email.new(email_params)

    respond_to do |format|
      if @email.save
        format.html { redirect_to thanks_path, notice: 'Email was successfully created.' }
        format.json { render :show, status: :created, location: thanks_path }
      else
        format.html { render :new }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emails/1
  # PATCH/PUT /emails/1.json
  def update
    respond_to do |format|
      if @email.update(email_params)
        format.html { redirect_to @email, notice: 'Email was successfully updated.' }
        format.json { render :show, status: :ok, location: @email }
      else
        format.html { render :edit }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @email.destroy
    respond_to do |format|
      format.html { redirect_to emails_url, notice: 'Email was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email
      @email = Email.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_params
      params.require(:email).permit(:email_address, :firstname, :lastname)
    end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: [:show, :edit, :update, :destroy]

  # GET /neighborhoods
  # GET /neighborhoods.json
  def index
    @neighborhoods = Neighborhood.all
  end

  # GET /neighborhoods/1
  # GET /neighborhoods/1.json
  def show
  end

  # GET /neighborhoods/new
  def new
    @neighborhood = Neighborhood.new
  end

  # GET /neighborhoods/1/edit
  def edit
  end

  # POST /neighborhoods
  # POST /neighborhoods.json
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)

    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to new_email_path, notice: 'Neighborhood was successfully created.' }
        format.json { render :show, status: :created, location: @neighborhood }
      else
        format.html { render :new }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighborhoods/1
  # PATCH/PUT /neighborhoods/1.json
  def update
    respond_to do |format|
      if @neighborhood.update(neighborhood_params)
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully updated.' }
        format.json { render :show, status: :ok, location: @neighborhood }
      else
        format.html { render :edit }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighborhoods/1
  # DELETE /neighborhoods/1.json
  def destroy
    @neighborhood.destroy
    respond_to do |format|
      format.html { redirect_to neighborhoods_url, notice: 'Neighborhood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighborhood
      @neighborhood = Neighborhood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighborhood_params
      params.require(:neighborhood).permit(:favorite_hood, :city_name, :moving_to_city_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def email
  end

  def thanks
  	@email = Email.last
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HoodLove</title>
	 

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

</head>
<body>
	
<%= link_to root_path do %>
  <h1><i class="glyphicon glyphicon-heart"></i> Hood Love</h1>
<% end %>

  
   <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <nav>
                <ul class="nav masthead-nav">
                   
                </ul>
              </nav>
            </div>
          </div>
          <div class="inner cover">
            <%= yield %>
          </div>
          <div class="mastfoot">
            <div class="inner">
              <p>Destiny's Child Production @copy; 2015</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  

</body>
</html>

app/views/neighborhoods/_form.html.erb
<%= form_for(@neighborhood) do |f| %>
  <% if @neighborhood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@neighborhood.errors.count, "error") %> prohibited this neighborhood from being saved:</h2>

      <ul>
      <% @neighborhood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :favorite_hood %><br>
    <%= f.text_field :favorite_hood, class: "black-font-text" %>
  </div>
  <div class="field">
    <%= f.label :city_name %><br>
    <%= f.text_field :city_name, class: "black-font-text" %>
  </div>
  <div class="field">
    <%= f.label :moving_to_city_name %><br>
    <%= f.text_field :moving_to_city_name, class: "black-font-text" %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit class: "btn btn-info" %>
  </div>
<% end %>

app/views/neighborhoods/edit.html.erb
<h1>Editing Neighborhood</h1>

<%= render 'form' %>

<%= link_to 'Show', @neighborhood %> |
<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Neighborhoods</h1>

<table>
  <thead>
    <tr>
      <th>Favorite hood</th>
      <th>City name</th>
      <th>Moving to city name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @neighborhoods.each do |neighborhood| %>
      <tr>
        <td><%= neighborhood.favorite_hood %></td>
        <td><%= neighborhood.city_name %></td>
        <td><%= neighborhood.moving_to_city_name %></td>
        <td><%= link_to 'Show', neighborhood %></td>
        <td><%= link_to 'Edit', edit_neighborhood_path(neighborhood) %></td>
        <td><%= link_to 'Destroy', neighborhood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Neighborhood', new_neighborhood_path %>

app/views/neighborhoods/new.html.erb
<h1>New Neighborhood</h1>

<%= render 'form' %>

<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Favorite hood:</strong>
  <%= @neighborhood.favorite_hood %>
</p>

<p>
  <strong>City name:</strong>
  <%= @neighborhood.city_name %>
</p>

<p>
  <strong>Moving to city name:</strong>
  <%= @neighborhood.moving_to_city_name %>
</p>

<%= link_to 'Edit', edit_neighborhood_path(@neighborhood) %> |
<%= link_to 'Back', neighborhoods_path %>

app/views/welcome/Email.html.erb
<h1>Welcome#Email</h1>
<p>Find me in app/views/welcome/Email.html.erb</p>

app/views/welcome/Thanks.html.erb
<h1> Thanks for Visiting <%= @email.firstname %></h1>

app/views/welcome/index.html.erb
<h3>Lets Get Started</h3>
<%= link_to 'Lets Get Started', new_neighborhood_path %>